version: "3.9"

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    build: rabbitmq/
    ports:
      - 15672:15672

  border_validator:
    depends_on:
      - rabbitmq
    container_name: border_validator
    restart: always
    build: ../sources/rmq/app-border-validator/
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: rabbit
      RABBITMQ_PASSWORD: mq_password
      INCOMING_QUEUE_NAME: incoming
      BORDER_CORRIDOR_EXCHANGE: border_corridor
      PERSON_ROUTING_KEY: person.cmn
      CAR_ROUTING_KEY: car.cmn

  incoming:
    depends_on:
      - rabbitmq
    container_name: incoming
    restart: always
    build: ../sources/rmq/app-incoming-handler/
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: rabbit
      RABBITMQ_PASSWORD: mq_password
      INCOMING_EXCHANGE: incoming_handler
