spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        default_schema: management
        order_by:
          default_null_ordering: first
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    locations: classpath:db/migration/management
    sql-migration-prefix: V
    baseline-on-migrate: true
    schemas: management
  servlet:
    multipart:
      enabled: false
server:
  servlet:
    context-path: "/api"
